[versions]
accompanistPermissions = "0.37.3"
androidGradlePlugin = "8.13.2"
compose = "1.9.3"
coreSplashscreen = "1.2.0"
googleServices = "4.4.4"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
compose-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "compose" }

[plugins]
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
